[project]
name = "jazzy"
version = "0.1.0"
description = "Development environment for RoboStack ROS packages"
authors = ["Steve Walker <65963536+stevalkr@users.noreply.github.com>"]
channels = ["https://fast.prefix.dev/conda-forge", "https://prefix.dev/robostack-jazzy"]
platforms = ["linux-64", "osx-arm64"]

[dependencies]
make = "*"
ninja = "*"
cmake = "*"
python = "*"
pyright = "*"
compilers = "*"
pkg-config = "*"

numpy = "*"
scipy = "*"
scikit-learn = "*"

rosdep = "*"
ros-jazzy-desktop = "*"
colcon-common-extensions = "*"

[target.linux-64.dependencies]
libgl-devel = "*"

[target.osx-arm64.pypi-dependencies]
torch = { version = ">=2.6.0", index = "https://download.pytorch.org/whl/cpu" }
torchvision = { version = ">=0.21.0", index = "https://download.pytorch.org/whl/cpu" }

[target.linux-64.pypi-dependencies]
torch = { version = ">=2.6.0", index = "https://download.pytorch.org/whl/cu124" }
torchvision = { version = ">=0.21.0", index = "https://download.pytorch.org/whl/cu124" }

